---
- name: add homebrew repositories
  homebrew_tap: tap={{item}} state=present
  with_items:
    - homebrew/versions
    - peco/peco
  
- name: install
  homebrew: state=present name={{item}}
  with_items:
    - coreutils
    - wget
    - tree
    - pwgen
    - pkg-config
    - cmake
    - ffmpeg
    - imagemagick
    - md5sha1sum
    - peco
    - bash
    - openssl
  
- name: install sshpass
  shell: |
    creates=/usr/local/Cellar/sshpass
    brew install https://raw.github.com/eugeneoden/homebrew/eca9de1/Library/Formula/sshpass.rb
  
- name: force link [bash, openssl]
  register: result
  changed_when: result.stderr.find('Already linked') == -1
  shell: brew link {{item}} --force
  with_items:
    - bash
    - openssl
  
- name: replace "/bin/sh" and "/bin/bash"
  sudo: yes
  register: result
  changed_when: result.rc == 2
  shell: "
    if ! readlink /bin/bash > /dev/null; then
      exit 2;
    fi;
    cp /bin/bash /bin/bash.system;
    cp /bin/sh /bin/sh.system;
    chmod a-x /bin/bash.system;
    chmod a-x /bin/sh.system;
    ln -fs /usr/local/bin/bash /bin/bash;
    ln -fs /usr/local/bin/bash /bin/sh;
  "
