---
- name: add homebrew repositories
  homebrew_tap: tap={{item}} state=present
  with_items:
    - peco/peco
  
- name: install
  homebrew: state=present name={{item}}
  with_items:
    - coreutils
    - wget
    - tree
    - pwgen
    - pkg-config
    - cmake
    - ffmpeg
    - imagemagick
    - md5sha1sum
    - peco
