---
- name: add homebrew repositories
  homebrew_tap: tap={{item}} state=present
  with_items:
    - homebrew/versions
    - peco/peco
  
- name: install
  homebrew: state=present name={{item}}
  with_items:
    - coreutils
    - wget
    - tree
    - pwgen
    - pkg-config
    - cmake
    - ffmpeg
    - imagemagick
    - graphviz
    - md5sha1sum
    - peco
    - bash
    - openssl
  
- name: install sshpass
  shell: |
    creates=/usr/local/Cellar/sshpass
    brew install https://raw.github.com/eugeneoden/homebrew/eca9de1/Library/Formula/sshpass.rb
  
- name: force link [bash, openssl]
  register: result
  changed_when: result.stderr.find('Already linked') == -1
  shell: brew link {{item}} --force
  with_items:
    - bash
    - openssl
