---
- name: add homebrew repositories
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/versions
  
- name: install
  homebrew: name={{ item }} state=latest
  with_items:
    - coreutils
    - wget
    - tree
    - pwgen
    - pkg-config
    - cmake
    - ffmpeg
    - imagemagick
    - graphviz
    - md5sha1sum
  
- name: install sshpass
  shell: |
    creates=/usr/local/Cellar/sshpass
    brew install http://git.io/sshpass.rb
