---
- name: get a data-uri of an icon
  changed_when: False
  register: icon_data
  script: get_data_uri.py {{icon_url}}
  
- name: copy search plugins
  template: >
    src=searchplugins/{{name}}.xml
    dest="{{profile_path.stdout}}/searchplugins/{{name}}.xml"
