---
- name: install firebrew
  register: firebrew
  gem: name=firebrew state=latest user_install=no
  
- name: rbenv rehash
  when: firebrew.changed
  shell: rbenv rehash
  
- name: get profile dir
  changed_when: False
  register: profile_path
  shell: firebrew profile --attribute=path
  
- name: copy user.js
  copy: src=user.js dest='{{profile_path.stdout}}/user.js'
  
- name: initialize search engines
  register: result
  changed_when: result.rc == 0
  failed_when: False
  shell: |
    ruby -e "
      require 'json';
      path = '{{profile_path.stdout}}/search.json';
      data = JSON.parse(File.read(path));
      data['directories'].each{|(k,v)|
        v['engines'].each{|vv|
          is_hiding = !['Google','Translate','Oxford','GitHub'].include?(vv['_name']);
          exit 1 if is_hiding && vv['_hidden'];
          vv['_hidden'] = is_hiding;
        };
      };
      File.write(path, JSON.generate(data));
    "
  
- name: create search plugin directory
  file: >
    state=directory
    path="{{profile_path.stdout}}/searchplugins"
  
- include: _search_engine.yml
  vars:
    name: gtranslate
    icon_url: https://translate.google.co.jp/favicon.ico
  
- include: _search_engine.yml
  vars:
    name: oxford
    icon_url: http://www.oxfordlearnersdictionaries.com/favicon.ico
  
- include: _search_engine.yml
  vars:
    name: github
    icon_url: https://github.com/favicon.ico 
  
- name: install add-ons
  firebrew: name='{{item}}' state=present
  with_items:
    - Japanese Language Pack
    - Vimperator
    - Evernote Web Clipper
    - Hatena Bookmark
    - Session Manager
    - Advanced Cookie Manager
