---
- name: install firebrew
  register: firebrew
  gem: name=firebrew state=latest user_install=no
  
- name: rbenv rehash
  when: firebrew.changed
  shell: rbenv rehash
  
- name: copy profiles
  copy: src=Firefox dest='~/Library/Application Support'
  
- name: get profile dir
  changed_when: False
  register: profile_path
  shell: firebrew profile --attribute=path
  
- name: create search plugin directory
  file: >
    state=directory
    path="{{ profile_path.stdout }}/searchplugins"
  
- include: _search_engine.yml
  vars:
    name: gtranslate
    icon_url: https://translate.google.co.jp/favicon.ico
  
- include: _search_engine.yml
  vars:
    name: oxford
    icon_url: http://www.oxfordlearnersdictionaries.com/favicon.ico
  
- include: _search_engine.yml
  vars:
    name: github
    icon_url: https://github.com/favicon.ico 
  
- name: install add-ons
  firebrew: name='{{ item }}' state=present
  with_items:
    - Vimperator
    - Evernote Web Clipper
    - Hatena Bookmark
    - Session Manager
    - Advanced Cookie Manager
