---
- name: install gcc
  homebrew: state=latest name={{ item }}
  with_items:
    - gcc48
    - gcc49
    - gcc5
  
- name: install clang
  register: clang
  homebrew: state=latest name={{ item }} install_options=with-clang,with-libcxx,rtti
  with_items:
    - llvm37
    - llvm38
  
- name: use install_name_tool to the libclang.dylib of llvm38 (for clang_complete)
  when: clang.changed
  shell: |
    _path=$(brew --prefix llvm38)
    _target=${_path}/lib/llvm-3.8/lib/libclang.dylib
    chmod u+w ${_target}
    install_name_tool -change '@rpath/libLLVM-3.8.dylib' ${_path}/lib/llvm-3.8/lib/libLLVM-3.8.dylib ${_target}
    chmod u-w ${_target}
  
- name: install boost
  homebrew: state=latest name={{ item }} install_options=c++11
  with_items:
    - boost
  
- name: install Qt
  register: qt
  homebrew: name={{ item }} state=latest
  with_items:
    - qt5
  
- name: link apps Designer.app, etc
  when: qt.changed
  shell: brew linkapps
  
- name: get Qt directory
  changed_when: false
  register: qt_dir
  shell: brew --prefix qt5
  
- name: copy zsh profile for Qt
  template: |
    src=qt_profile.sh
    dest=~/.zprofile.d/qt.sh
