---
- name: install
  homebrew: name=mysql state=present
  
- name: copy launch config file
  copy: |
    src={{ mysql_launch_config }}.plist
    dest={{ mysql_launch_config_path }}
  
- name: apply launch config file
  shell: |
    launchctl unload -w {{ mysql_launch_config_path }}
    launchctl load -w {{ mysql_launch_config_path }}
