---
- name: install
  homebrew: name={{item}} state=present
  with_items:
    - mysql
  
- name: copy the configure file
  copy: |
    src=homebrew.mxcl.mysql.plist
    dest={{ mysql_plist }}
  
- name: apply the configure file
  shell: |
    launchctl unload -w {{ mysql_plist }}
    launchctl load -w {{ mysql_plist }}
