---
- name: install firebrew
  gem: name={{item}} state=present
  with_items:
    - firebrew
  
- name: install add-ons
  firebrew: name='{{item}}' state=present
  with_items:
    - Japanese Language Pack
    - Vimperator
    - Evernote Web Clipper
    - Hatena Bookmark
  
- name: get project root
  command: pwd
  register: result
  changed_when: False
  
- name: link .vimperatorrc
  file: >
    state=link
    force=yes
    src={{result.stdout}}/roles/firefox/files/{{item}}
    dest=~/.{{item}}
  with_items:
    - vimperatorrc
  
- name: create plugin dir
  file: >
    state=directory
    path=~/.vimperator/plugin
    
- name: clone plugins
  git: >
    repo=https://github.com/vimpr/vimperator-plugins
    dest=~/.vimperator/vimperator-plugins
  
- name: set plugins
  file: >
    state=link
    src=~/.vimperator/vimperator-plugins/appendAnchor.js
    dest=~/.vimperator/plugin/appendAnchor.js
