---
- name: create ~/.vim/bundle
  file: |
    state=directory
    recurse=yes
    path=~/.vim/bundle

- name: git clone neobundle
  git: |
    repo=https://github.com/Shougo/neobundle.vim.git
    dest=~/.vim/bundle/neobundle.vim

- name: install neobundle-cmd
  gem: name=neobundle state=latest user_install=no

- name: bundle install
  shell: neobundle install
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc == 1
