---
- name: add repository
  shell: |
    creates=/usr/local/Library/Taps/{{ item.lower() }}
    brew tap {{ item }}
  with_items:
    - KazuakiM/homebrew-splhack
  
- name: install ctags
  register: ctags
  homebrew: name=ctags state=latest update_homebrew=yes
  
- name: link ctags
  when: ctags.changed
  shell: brew link --overwrite ctags
  
- name: install
  register: macvim
  homebrew: name={{ item.name }} install_options={{ item.options }} state=latest update_homebrew=yes
  with_items:
    - name: cscope
      options:
    
    - name: lua
      options:
    
    - name: cmigemo-mk
      options: HEAD
    
    - name: ctags-objc-ja
      options: HEAD
    
    - name: macvim-kaoriya
      options: HEAD,with-lua,with-cscope
  
- name: link apps
  when: macvim.changed
  shell: brew linkapps
  
- name: set rc
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - src: macvim-kaoriya_profile.sh
      dest: ~/.zprofile.d/macvim-kaoriya.sh
    
    - src: macvim-kaoriya_rc.sh
      dest: ~/.zshrc.d/macvim-kaoriya.sh
    
    - src: vim_profile.sh
      dest: ~/.zprofile.d/vim.sh
  
- name: make directories
  file: state=directory path={{ item }}
  with_items:
    - ~/.vim-tmp
  
- name: get project root
  register: result
  changed_when: False
  shell: pwd
  
- name: link vimrc
  file: |
    state=link
    force=yes
    src={{ result.stdout }}/roles/app/vim/files/{{ item }}
    dest=~/.{{ item }}
  with_items:
    - vimrc
    - gvimrc
