---
- name: install packages
  homebrew: state=present name={{ item }}
  with_items:
    - rbenv
    - ruby-build
    - rbenv-gemset
    - rbenv-gem-rehash
    - readline
    - openssl

- name: get rbenv config
  changed_when: false
  register: rbenv_config
  shell: rbenv init --no-rehash - zsh

- name: rbenv config
  template: src=rbenv.sh dest=~/.zshrc.d/rbenv.sh

- name: install ruby
  register: ruby
  shell: |
    creates=~/.rbenv/versions/{{ item }}/bin/ruby
    rbenv install {{ item }}
  with_items:
    - 2.0.0-p594
    - 2.1.4
    - 2.2.0

- name: using latest version
  when: ruby.changed
  shell: |
    rbenv global 2.2.0
    rbenv rehash

- name: install bundler
  register: bundler
  gem: name=bundler state=present

- name: rehash
  when: bundler.changed
  shell: rbenv rehash
