---
- name: install packages
  homebrew: state=latest name={{ item }}
  with_items:
    - rbenv
    - ruby-build
    - rbenv-gemset
    - readline

- name: install ruby
  register: ruby
  shell: |
    creates=~/.rbenv/versions/{{ item }}/bin/ruby
    rbenv install {{ item }}
  with_items:
    - 2.0.0-p594
    - 2.1.4
    - 2.2.2
    - 2.3.0

- name: using latest version
  when: ruby.changed
  shell: |
    rbenv global 2.2.2
    rbenv rehash

- name: ruby config
  copy: src=ruby_profile.sh dest=~/.zprofile.d/ruby.sh

- name: install basic gems
  register: gems
  gem: name={{ item }} state=latest user_install=no
  with_items:
    - bundler
    - rails

- name: rehash
  when: gems.changed
  shell: rbenv rehash
