---
- name: rbenv config
  copy: src=rbenv.sh dest=~/.zshrc.d/rbenv.sh
  
- name: install packages
  homebrew: state=present name={{ item }}
  with_items:
    - rbenv
    - ruby-build
    - rbenv-gemset
    - rbenv-gem-rehash
    - readline
    - openssl

- name: install ruby
  register: ruby
  shell: |
    creates=~/.rbenv/versions/{{ item }}/bin/ruby
    rbenv install {{ item }}
  with_items:
    - 2.0.0-p594
    - 2.1.4
    - 2.2.0-preview1

- name: using latest version
  when: ruby.changed
  shell: |
    rbenv global 2.1.4
    rbenv rehash

- name: install bundler
  register: bundler
  gem: name=bundler state=present

- name: rehash
  when: bundler.changed
  shell: rbenv rehash
