---
- name: install packages
  homebrew: state=present name={{ item }}
  with_items:
    - rbenv
    - ruby-build
    - rbenv-gemset
    - rbenv-gem-rehash
    - readline
    - openssl

- name: install ruby
  register: ruby
  shell: |
    creates=~/.rbenv/versions/{{ item }}/bin/ruby
    rbenv install {{ item }}
  with_items:
    - 2.0.0-p594
    - 2.1.4
    - 2.2.2

- name: using latest version
  when: ruby.changed
  shell: |
    rbenv global 2.2.2
    rbenv rehash

- name: get latest ruby dir
  changed_when: false
  register: ruby_dir
  shell: dirname `rbenv which ruby`

- name: ruby config
  template: src=ruby.sh dest=~/.zprofile.d/ruby.sh

- name: install bundler
  register: bundler
  gem: name=bundler state=present

- name: rehash
  when: bundler.changed
  shell: rbenv rehash
