---
- name: install packages
  homebrew: state=latest name={{ item }}
  with_items:
    - rbenv
    - ruby-build
    - rbenv-gemset
    - rbenv-gem-rehash
    - readline

- name: install ruby
  register: ruby
  shell: |
    creates=~/.rbenv/versions/{{ item }}/bin/ruby
    rbenv install {{ item }}
  with_items:
    - 2.0.0-p594
    - 2.1.4
    - 2.2.2

- name: using latest version
  when: ruby.changed
  shell: |
    rbenv global 2.2.2
    rbenv rehash

- name: ruby config
  copy: src=ruby_profile.sh dest=~/.zprofile.d/ruby.sh

- name: install bundler
  register: bundler
  gem: name=bundler state=latest user_install=no

- name: rehash
  when: bundler.changed
  shell: rbenv rehash
