---
- name: install
  homebrew: state=present name={{item}}
  with_items:
    - coreutils
    - wget
    - tree
    - pwgen
    - pkg-config
    - cmake
    - ffmpeg
    - md5sha1sum

- name: install cask packages
  sudo: yes
  homebrew_cask: name={{item}} state=present
  with_items:
    - virtualbox
    - vagrant
    - xquartz
