---
- name: install
  homebrew: state=latest name={{ item }}
  with_items:
    - ghc
    - cabal-install
  
- name: copy cabal zsh profile
  copy: src={{ item }} dest=~/.zprofile.d/{{ item }}
  with_items:
    - cabal_profile.sh
  
- name: update cabal packages
  shell: cabal update
