---
- name: install
  homebrew: name=redis state=present
  
- name: copy launch config file
  copy: |
    src={{ redis_launch_config }}.plist
    dest={{ redis_launch_config_path }}
  
- name: apply launch config file
  shell: |
    launchctl unload -w {{ redis_launch_config_path }}
    launchctl load -w {{ redis_launch_config_path }}
    launchctl start {{ redis_launch_config }}
