---
- name: install
  homebrew: name=direnv state=present

- name: get direnv config
  changed_when: false
  register: direnv_config
  shell: direnv hook zsh

- name: set direnv config
  template: src=direnv.sh dest=~/.zshrc.d/direnv.sh
