---
- name: install nodebrew
  homebrew: name=nodebrew state=latest

- name: copy config files
  copy: src=node_profile.sh dest=~/.zprofile.d/node.sh

- name: install node
  register: node
  shell: |
    creates=~/.nodebrew/node/{{ item }}
    mkdir -p  ~/.nodebrew/src/{{ item }}/
    nodebrew install {{ item }}
  with_items:
    - v0.12.7

- name: use node
  when: node.changed
  shell: nodebrew use v0.12.7
