---
- name: install nodebrew
  homebrew: name=nodenv state=latest

- name: copy config files
  copy: src=node_profile.sh dest=~/.zprofile.d/node.sh

- name: install node
  shell: |
    nodenv versions | grep {{ item }} && {
      nodenv install {{ item }}
      nodenv global {{ item }}
      nodenv rehash
    }
  with_items:
    - 6.2.2
