---
- name: install
  homebrew_cask: name={{item}} state=present
  with_items:
    - virtualbox
    - vagrant
    - boot2docker
  
- name: install fig
  homebrew: name={{item}} state=latest update_homebrew=yes
  with_items:
    - fig
