- name: install
  homebrew_cask: name={{ item }} state=present
  with_items:
    - karabiner

- name: copy private.xml
  copy: |
    src=private.xml
    dest='~/Library/Application Support/Karabiner/private.xml'

- name: export current settings
  changed_when: False
  shell: |
    /Applications/Karabiner.app/Contents/Library/bin/karabiner export > /tmp/karabiner_settings.sh

- name: copy settings
  register: result
  copy: src=settings.sh dest=/tmp/karabiner_settings.sh mode=0755

- name: import settings
  when: result.changed
  command: /tmp/karabiner_settings.sh
