---
- name: get user name
  command: whoami
  register: result
  changed_when: False
  
- name: change default shell
  sudo: yes
  command: chsh -s /bin/zsh {{result.stdout}}
  
- name: make directory
  file: state=directory path={{item}}
  with_items:
    - ~/.zprofile.d
    - ~/.zshrc.d
  
- name: create files
  copy: src={{item}}.sh dest=~/.{{item}}
  with_items:
    - zprofile
    - zshrc
