---
- name: install
  homebrew: name={{ item }} state=latest
  with_items:
    - zsh
  
- name: get user name
  command: whoami
  register: result
  changed_when: False
  
- name: change default shell
  sudo: yes
  command: chsh -s /usr/local/bin/zsh {{ result.stdout }}
  
- name: make directory
  file: state=directory path={{ item }}
  with_items:
    - ~/.zprofile.d
    - ~/.zshrc.d
  
- name: get project root
  register: result
  changed_when: False
  shell: pwd
  
- name: link files
  file: |
    state=link
    force=yes
    src={{ result.stdout }}/roles/base/zsh/files/{{ item }}.sh
    dest=~/.{{ item }}
  with_items:
    - zprofile
    - zshrc
