---
- name: install
  homebrew: name={{item}} state=latest update_homebrew=yes
  with_items:
    - postgresql
  
- name: copy file
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
    - src: profile.sh
      dest: ~/.zprofile.d/postgresql.sh
  
- name: get install path
  register: result
  changed_when: False
  shell: >
    cd $(dirname $(which psql))/$(dirname $(readlink $(which psql)))/../; pwd
  
- name: link auto run file
  file: src={{item.src}} dest={{item.dest}} state=link
  with_items:
    - src: "{{result.stdout}}/homebrew.mxcl.postgresql.plist"
      dest: ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
  
- name: register auto run
  command: >
    launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
