scriptencoding utf-8
filetype detect
syntax on

colorscheme delek
set guioptions+=a

if has('gui_macvim')
  set transparency=3
  set guifont=Menlo:h12
  set lines=90 columns=200
  set guioptions-=T
endif
