---
- name: install homebrew
  shell: |
    creates=/usr/local/bin/brew
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

- name: update formula
  homebrew: update_homebrew=yes

- name: add homebrew-cask repository
  homebrew_tap: tap=caskroom/cask state=present

- name: install homebrew-cask
  homebrew: name=brew-cask state=latest
  
- name: copy homebrew-cask config
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - src: homebrew_profile.sh
      dest: ~/.zprofile.d/homebrew.sh
