---
- name: rbenv config
  copy: src=rbenv.sh dest=~/.zprofile.d/rbenv.sh
  
- name: install packages
  homebrew: state=present name={{item}}
  with_items:
    - rbenv
    - ruby-build
    - rbenv-gemset
    - rbenv-gem-rehash
    - readline
    - openssl

- name: install ruby
  shell: >
    creates=~/.rbenv/versions/{{item}}/bin/ruby
    rbenv install {{item}};
  with_items:
    - 1.9.3-p547
    - 2.0.0-p481
    - 2.1.1

- name: using latest version
  shell: >
    rbenv global 2.1.1;
    rbenv rehash;

- name: install bundler
  gem: name={{item}} state=present
  with_items:
    - bundler

- name: rehash
  command: rbenv rehash
